---
title: "Week 7"
author: "Heng Javier"
date: "2023-10-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#I. All about ggplot2 package
```{r,echo=TRUE,eval=F}
#Structure of code:
ggplot(data = [dataset],
 mapping = aes(x = [x-variable],
 y = [y-variable])) +
 geom_xxx() +
 other options
```
```{r,echo=TRUE,eval=TRUE}
#Load the Palmer Penguins library 
library(tidyverse)
library(dplyr)
library(palmerpenguins)
glimpse(penguins)
```
```{r,echo=TRUE,eval=TRUE}
#Recreating the plot in Lecture 7:
ggplot(data=penguins,
       mapping=aes(x=bill_depth_mm,
                   y=bill_length_mm,
                   colour=species)) +
  geom_point() +
  labs(title="Bill Length against Bill Depth",
       subtitle="Dimensions for Adelie, Chinstrap and Gentoo Penguins",
       x="Bill depth (mm)", y="Bill length (mm)",
       colour="Species", 
       caption="Source: Palmer Station LTER/palmerpenguins package"
       )
 #OR
 ggplot(penguins)+ #Data Layer    
       aes(x=bill_depth_mm,
                   y=bill_length_mm,
                   colour=species) + #Aesthetic Layer
  geom_point() + #Geometric Layer
  labs(title="Bill Length against Bill Depth",
       subtitle="Dimensions for Adelie, Chinstrap and Gentoo Penguins",
       x="Bill depth (mm)", y="Bill length (mm)",
       colour="Species", 
       caption="Source: Palmer Station LTER/palmerpenguins package"
       ) 
```
```{r,echo=TRUE,eval=TRUE}
#Colorblind
ggplot(penguins) + aes(x = bill_depth_mm, y = bill_length_mm,
 colour = species) +
 geom_point() + scale_colour_viridis_d()

```
```{r,echo=TRUE,eval=TRUE}
#Shape
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = island)) +
 geom_point() + scale_colour_viridis_d()

```
```{r,echo=TRUE,eval=TRUE}
#Size
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species, shape = species,
 size = body_mass_g)) +
 geom_point() + scale_colour_viridis_d()
```
```{r,echo=TRUE,eval=TRUE}
#Alpha
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = species, size = body_mass_g, alpha = flipper_length_mm)) +
 geom_point() + scale_colour_viridis_d()

```
```{r,echo=TRUE,eval=TRUE}
#Mapping
ggplot(penguins) +
 aes(x = bill_depth_mm,
 y = bill_length_mm,
 size = body_mass_g,
 alpha = flipper_length_mm) +
 geom_point()
```
```{r,echo=TRUE,eval=TRUE}
#Setting
ggplot(penguins) +
 aes(x = bill_depth_mm,
 y = bill_length_mm) +
 geom_point(size = 2, alpha = 0.5)

```
```{r,echo=TRUE,eval=TRUE}
#Faceting (by island)
ggplot(penguins) +
 aes(x = bill_depth_mm,
 y = bill_length_mm) +
 geom_point() +
 facet_grid(species ~ island)

```
```{r,echo=TRUE,eval=TRUE}
#Faceting Grid (by sex)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(species ~ sex)

```
```{r,echo=TRUE,eval=TRUE}
#Faceting Grid(by sex and species)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(sex ~ species)

```
```{r,echo=TRUE,eval=TRUE}
#Faceting Wrap (by species)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species)

```
```{r,echo=TRUE,eval=TRUE}
#Faceting Wrap by species, but sorted into 2 columns
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species, ncol = 2)

```
```{r,echo=TRUE,eval=TRUE}
#Facet and colour
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d()

```
```{r,echo=TRUE,eval=TRUE}
#Facet and color, with no legend
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d() +
 guides(color = "none")
```
#II. Visualising numeric variables
```{r,echo=TRUE,eval=TRUE}
#Access openintro library
library(openintro)
glimpse(loans_full_schema)
```
```{r,echo=TRUE,eval=TRUE}
#Select Variable
loans <- loans_full_schema %>%
 select(loan_amount, interest_rate, term, grade,
 state, annual_income, homeownership, debt_to_income)
glimpse(loans)
```
```{r,echo=TRUE,eval=F}
#Histogram
ggplot(loans) + aes(x = loan_amount) +
 geom_histogram()

```
```{r,echo=TRUE,eval=TRUE}
#binwidth = 1000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 1000)

```
```{r,echo=TRUE,eval=TRUE}
# binwidth = 5000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 5000)

```
```{r,echo=TRUE,eval=TRUE}
# binwidth = 20000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 20000)

```
```{r,echo=TRUE,eval=TRUE}
#Customizing histogram (adding title, x and y axis)
ggplot(loans, aes(x = loan_amount)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)", y = "Frequency", title = "Amounts of Lending Club loans" )
```
```{r,echo=TRUE,eval=TRUE}
#Fill with a categorical variable 
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
 geom_histogram(binwidth = 5000, alpha = 0.5) +
 labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans")

```
```{r,echo=TRUE,eval=TRUE}
#Facet with categorical variable
ggplot(loans, aes(x = loan_amount, fill = homeownership)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans") +
 facet_wrap(~ homeownership, nrow = 3)


```
```{r,echo=TRUE,eval=TRUE}
#Density plot
ggplot(loans, aes(x = loan_amount)) +
 geom_density()
```
```{r,echo=TRUE,eval=TRUE}
#Density plot with adjusted bandwidth 
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 0.5)

```
```{r,echo=TRUE,eval=TRUE}
#default bandwidth
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 1) 

```
```{r,echo=TRUE,eval=TRUE}
#bandwidth = 2
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2)

```
```{r,echo=TRUE,eval=TRUE}
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2) +
 labs( x = "Loan amount ($)", y = "Density", title = "Amounts of Lending Club loans" )

```
```{r,echo=TRUE,eval=TRUE}
#Customizing density plot (adding title, x and y axis)
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2) +
 labs( x = "Loan amount ($)", y = "Density", title = "Amounts of Lending Club loans" )

```
```{r,echo=TRUE,eval=TRUE}
#Adding categorical variable to density plot
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
 geom_density(adjust = 2, alpha = 0.5) +
 labs(x = "Loan amount ($)",y = "Density",title = "Amounts of Lending Club loans", fill = "Homeownership")
```
```{r,echo=TRUE,eval=TRUE}
#Boxplot
ggplot(loans, aes(x = interest_rate)) +
 geom_boxplot()
```
```{r,echo=TRUE,eval=TRUE}
#Box Plot with outliers
ggplot(loans, aes(x = annual_income)) +
 geom_boxplot()

```
```{r,echo=TRUE,eval=TRUE}
#Customizing boxplot (adding title, x and y axis)
ggplot(loans, aes(x = interest_rate)) +geom_boxplot() +labs(x = "Interest rate (%)",y = NULL,
 title = "Interest rates of Lending Club loans") +
 theme( axis.ticks.y = element_blank(), axis.text.y = element_blank() )

```
```{r,echo=TRUE,eval=TRUE}
#Adding categorical variable to boxplot
ggplot(loans, aes(x = interest_rate,
 y = grade)) +
 geom_boxplot() +
 labs(x = "Interest rate (%)",y = "Grade",title = "Interest rates of Lending Club loans",subtitle = "by grade of loan")
```
```{r,echo=TRUE,eval=TRUE}
#Scatterplot
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
 geom_point()

```
```{r,echo=TRUE,eval=TRUE}
#Hex Plot
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
 geom_hex()
```
```{r,echo=TRUE,eval=TRUE}
#Hex Plot (filtered)
ggplot(loans %>% filter(debt_to_income < 100),
 aes(x = debt_to_income, y = interest_rate)) +
 geom_hex()

```
#III. Visualising Categoric Variables
```{r,echo=TRUE,eval=TRUE}
#Bar Plot
ggplot(loans, aes(x = homeownership)) +
 geom_bar()

```
```{r,echo=TRUE,eval=TRUE}
#Segmented Bar Plot (by count)
ggplot(loans, aes(x = homeownership,
 fill = grade)) +
 geom_bar()

```
```{r,echo=TRUE,eval=TRUE}
#Segmented Bar Plot (by percentage)
ggplot(loans, aes(x = homeownership, fill = grade)) +
 geom_bar(position = "fill")

```
```{r,echo=TRUE,eval=TRUE}
ggplot(loans, aes(y = homeownership, fill = grade)) + geom_bar(position = "fill") +
labs( x = "Proportion", y = "Homeownership", fill = "Grade", title = "Grades of Lending Club loans", subtitle="and homeownership of lendee")
```
IV. Visualizing variable of varied types
```{r,echo=TRUE,eval=TRUE}
#Violin Plot
ggplot(loans, aes(x = homeownership, y = loan_amount)) +
 geom_violin()
```
```{r,echo=TRUE,eval=TRUE}
#Ridge Plot
library(ggridges)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) +
 geom_density_ridges(alpha = 0.5)

```





