---
title: "Week 9 Challenge"
author: "Heng Javier"
date: "2023-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r,echo=TRUE,eval=TRUE}
#Tidy Data
library(tidyverse)
tidydata <- tribble(
~country, ~year, ~cases, ~population,
"Afghanistan", 1999, 745, 19987071,
"Afghanistan", 2000, 2666, 20595360,
"Brazil", 1999, 37737, 172006362,
"Brazil", 2000, 80488, 174504898,
"China", 1999, 212258, 1272915272,
"China", 2000, 213766, 1280428583)
tidydata
```
```{r,echo=TRUE,eval=TRUE}
#Non-tidy Data
nontidydata <- tribble(
 ~country,~year,~rate,
"Afghanistan", 1999, "745/19987071",
"Afghanistan", 2000, "2666/20595360",
"Brazil", 1999, "37737/172006362",
"Brazil", 2000, "80488/174504898",
"China", 1999, "212258/1272915272",
"China", 2000, "213766/1280428583")
nontidydata
```
```{r,echo=TRUE,eval=TRUE}
#Tidying nontidydata: Example 1
tidieddata <- nontidydata %>%
 separate(rate, into = c("cases",
 "population"),
 sep = "/")
tidieddata

newtidieddata <- tidieddata %>%
 pivot_longer(
 cols = cases:population,
 names_to = "measurement"
,
 values_to = "value"
 )
newtidieddata
```
```{r,echo=TRUE,eval=TRUE}
#Tidying Data: Example 2
df <- tribble(
 ~id, ~bp1, ~bp2,
 "A", 100, 120,
 "B", 140, 115,
 "C", 120, 125
)
df

df %>%
 pivot_longer(
 cols = bp1:bp2,
 names_to = "measurement",
 values_to = "value"
 )

```
```{r,echo=TRUE,eval=TRUE}
#Reshaping data: Example 3
newtidieddata

newtidieddata %>%
 pivot_wider(names_from="measurement",
 values_from="value")
```
```{r,echo=TRUE,eval=TRUE}
#Reshaping data: Example 4
df <- tribble(
 ~id, ~measurement, ~value,
 "A", "bp1", 100,
 "B", "bp1", 140,
 "B", "bp2", 115,
 "A", "bp2", 120,
 "A", "bp3", 105
)
df

df %>%
 pivot_wider(
 names_from = measurement,
 values_from = value
 )

```
```{r,echo=TRUE,eval=TRUE}
#Question 1 
tidybillboard<- billboard%>%
pivot_longer(
  cols= starts_with("wk"),
  names_to = "week",
  values_to = "rank",
  values_drop_na=T,
  )

tidybillboard <- mutate(tidybillboard,week = parse_number(week))

tidybillboard

ggplot(data = tidybillboard, mapping = aes(x=week, y=rank), environment = parent.frame()) + geom_line()
ggtitle("Graph of Rank against Week ")
```
```{r,echo=TRUE,eval=TRUE}

```
```{r,echo=TRUE,eval=TRUE}

```
```{r,echo=TRUE,eval=TRUE}

```
```{r,echo=TRUE,eval=TRUE}

```
```{r,echo=TRUE,eval=TRUE}

```
```{r,echo=TRUE,eval=TRUE}

```
```{r,echo=TRUE,eval=TRUE}

```
